### ISSUE TITLE
Docker localhost:5000 SSL timeout

### ISSUE THREAD

**Issue by Oneiroi** [mwielgoszewski/doorman#101]
Hello,

I am getting a strange issue,

1. http://localhost:5000/ correctly redirects to https://localhost:5000/
2. https://localhost:5000/ does not respond and the request times out

Attempting diagnostics I ran 
```
docker exec -t -i xxxx /bin/bash
bash-4.3# curl 127.0.0.1:5000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="https://127.0.0.1:5000/">https://127.0.0.1:5000/</a>.  If not click the link.bash-4.3# 
bash-4.3# curl https://127.0.0.1:5000/
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:5000 
```

And from the host system

```
curl https://localhost:5000/manage/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
* Operation timed out after 10002 milliseconds with 0 out of 0 bytes received
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (28) Operation timed out after 10002 milliseconds with 0 out of 0 bytes received
```

Unsure on how to proceed at this point in time 

Repo is at commit: 3de5d868e208c3d3c3d3bdca2088d64bd0035da4
Docker doorman image built from this commit, also using postgres:latest from docker hub to provide and link the postgres service

docker-compose.yml in use is:

```yaml
version: '3'

services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - "DEBUG=true"
            - "POSTGRES_PASSWORD=t00m4nys3cr3t5"
    doorman:
        image: doorman:latest
        ports:
            - "5000:5000"
        environment:
            - "DOORMAN_ENROLL_SECRET=foo"
            - "DOORMAN_SECRETS_KEY=doorman"
            - "POSTGRES_USER=doorman"
            - "POSTGRES_PASSWORD=t00m4nys3cr3t5"
            - "POSTGRES_PORT=postgres"
```
